### ISSUE TITLE
Incomplete the Mobile Version Images

### ISSUE THREAD

**Issue by CELYNEBIRUNGI** [Ochiengsteven/art-fest#6]
Hi@ Ochieng Steven,
    Great job on this project. However, you need  to work the mobile version
![Screenshot 2023-04-27 101914](https://user-images.githubusercontent.com/113887926/234790527-354b3b88-1dd7-44ce-a310-560c23a58547.png)

the images in the mobile version aren't the right margin size

**Comment by Ochiengsteven** [comment]
Thank you for your review 😃
I have made the required changes ♻️
